# Generated by Django 3.2.5 on 2021-07-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('age', models.IntegerField()),
                ('education', models.CharField(choices=[('highSchool', 'HighSchool'), ('bachelor', 'Bachelor'), ('phd', 'PhD'), ('master', 'Master')], max_length=50)),
                ('occupation', models.CharField(max_length=50)),
                ('userId', models.CharField(default='41790279dd8f4fff8c81b4b1b4c4717d', max_length=255, unique=True)),
            ],
        ),
    ]
