# Generated by Django 3.2.5 on 2021-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsubject',
            name='username',
        ),
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='16cb83c957b94b8c820b79b38b163465', max_length=255, unique=True),
        ),
    ]
