# Generated by Django 3.2.5 on 2021-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_auto_20210726_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='f3172605ede511ebb03c2c4d5464fb8b', max_length=255, unique=True),
        ),
    ]
