# Generated by Django 3.2.5 on 2021-08-01 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_alter_testsubject_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='7fc2d9d0f2d811eb98862c4d5464fb8b', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='SleepLevelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=50)),
                ('testSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.testsubject')),
            ],
        ),
    ]
