# Generated by Django 3.2.5 on 2021-08-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0008_auto_20210801_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeplevellog',
            name='sleepLevel',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='9b806b6ef2d811ebb37f2c4d5464fb8b', max_length=255, unique=True),
        ),
    ]
