# Generated by Django 3.2.5 on 2021-08-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_auto_20210801_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='f25dcc58f2da11eba0302c4d5464fb8b', max_length=255, unique=True),
        ),
    ]
