# Generated by Django 3.2.5 on 2021-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0012_auto_20210805_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singlelog',
            old_name='eyeClosureile',
            new_name='eyeClosure',
        ),
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='2ac82224f5e711eba6cb2c4d5464fb8b', max_length=255, unique=True),
        ),
    ]
