# Generated by Django 3.2.6 on 2021-08-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0014_alter_testsubject_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default='5e768526faab11eb9297eeb83f6bd8c4', max_length=255, unique=True),
        ),
    ]
