# Generated by Django 3.2.6 on 2021-08-26 12:08

import BackEnd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0015_alter_testsubject_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubject',
            name='userId',
            field=models.CharField(default=BackEnd.models.get_uuid, max_length=255, unique=True),
        ),
    ]
